// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zmqpbexample.proto

#ifndef PROTOBUF_zmqpbexample_2eproto__INCLUDED
#define PROTOBUF_zmqpbexample_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_zmqpbexample_2eproto();
void protobuf_AssignDesc_zmqpbexample_2eproto();
void protobuf_ShutdownFile_zmqpbexample_2eproto();

class ZmqPBExample;

// ===================================================================

class ZmqPBExample : public ::google::protobuf::Message {
 public:
  ZmqPBExample();
  virtual ~ZmqPBExample();
  
  ZmqPBExample(const ZmqPBExample& from);
  
  inline ZmqPBExample& operator=(const ZmqPBExample& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ZmqPBExample& default_instance();
  
  void Swap(ZmqPBExample* other);
  
  // implements Message ----------------------------------------------
  
  ZmqPBExample* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ZmqPBExample& from);
  void MergeFrom(const ZmqPBExample& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string foo = 1;
  inline bool has_foo() const;
  inline void clear_foo();
  static const int kFooFieldNumber = 1;
  inline const ::std::string& foo() const;
  inline void set_foo(const ::std::string& value);
  inline void set_foo(const char* value);
  inline void set_foo(const char* value, size_t size);
  inline ::std::string* mutable_foo();
  inline ::std::string* release_foo();
  
  // @@protoc_insertion_point(class_scope:ZmqPBExample)
 private:
  inline void set_has_foo();
  inline void clear_has_foo();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* foo_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_zmqpbexample_2eproto();
  friend void protobuf_AssignDesc_zmqpbexample_2eproto();
  friend void protobuf_ShutdownFile_zmqpbexample_2eproto();
  
  void InitAsDefaultInstance();
  static ZmqPBExample* default_instance_;
};
// ===================================================================


// ===================================================================

// ZmqPBExample

// required string foo = 1;
inline bool ZmqPBExample::has_foo() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ZmqPBExample::set_has_foo() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ZmqPBExample::clear_has_foo() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ZmqPBExample::clear_foo() {
  if (foo_ != &::google::protobuf::internal::kEmptyString) {
    foo_->clear();
  }
  clear_has_foo();
}
inline const ::std::string& ZmqPBExample::foo() const {
  return *foo_;
}
inline void ZmqPBExample::set_foo(const ::std::string& value) {
  set_has_foo();
  if (foo_ == &::google::protobuf::internal::kEmptyString) {
    foo_ = new ::std::string;
  }
  foo_->assign(value);
}
inline void ZmqPBExample::set_foo(const char* value) {
  set_has_foo();
  if (foo_ == &::google::protobuf::internal::kEmptyString) {
    foo_ = new ::std::string;
  }
  foo_->assign(value);
}
inline void ZmqPBExample::set_foo(const char* value, size_t size) {
  set_has_foo();
  if (foo_ == &::google::protobuf::internal::kEmptyString) {
    foo_ = new ::std::string;
  }
  foo_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ZmqPBExample::mutable_foo() {
  set_has_foo();
  if (foo_ == &::google::protobuf::internal::kEmptyString) {
    foo_ = new ::std::string;
  }
  return foo_;
}
inline ::std::string* ZmqPBExample::release_foo() {
  clear_has_foo();
  if (foo_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = foo_;
    foo_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_zmqpbexample_2eproto__INCLUDED
