// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zmqpbexample.proto

#ifndef PROTOBUF_zmqpbexample_2eproto__INCLUDED
#define PROTOBUF_zmqpbexample_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
class RPCAddRequest;
class RPCAddRequestDefaultTypeInternal;
extern RPCAddRequestDefaultTypeInternal _RPCAddRequest_default_instance_;
class RPCAddResponse;
class RPCAddResponseDefaultTypeInternal;
extern RPCAddResponseDefaultTypeInternal _RPCAddResponse_default_instance_;
class RPCReverseRequest;
class RPCReverseRequestDefaultTypeInternal;
extern RPCReverseRequestDefaultTypeInternal _RPCReverseRequest_default_instance_;
class RPCReverseResponse;
class RPCReverseResponseDefaultTypeInternal;
extern RPCReverseResponseDefaultTypeInternal _RPCReverseResponse_default_instance_;
class ZmqPBExampleRPCRequest;
class ZmqPBExampleRPCRequestDefaultTypeInternal;
extern ZmqPBExampleRPCRequestDefaultTypeInternal _ZmqPBExampleRPCRequest_default_instance_;
class ZmqPBExampleRPCResponse;
class ZmqPBExampleRPCResponseDefaultTypeInternal;
extern ZmqPBExampleRPCResponseDefaultTypeInternal _ZmqPBExampleRPCResponse_default_instance_;
class ZmqPBExampleRequest;
class ZmqPBExampleRequestDefaultTypeInternal;
extern ZmqPBExampleRequestDefaultTypeInternal _ZmqPBExampleRequest_default_instance_;
class ZmqPBExampleResponse;
class ZmqPBExampleResponseDefaultTypeInternal;
extern ZmqPBExampleResponseDefaultTypeInternal _ZmqPBExampleResponse_default_instance_;
class ZmqPBExampleWeather;
class ZmqPBExampleWeatherDefaultTypeInternal;
extern ZmqPBExampleWeatherDefaultTypeInternal _ZmqPBExampleWeather_default_instance_;
class ZmqPBExampleWorkerRequest;
class ZmqPBExampleWorkerRequestDefaultTypeInternal;
extern ZmqPBExampleWorkerRequestDefaultTypeInternal _ZmqPBExampleWorkerRequest_default_instance_;
class ZmqPBExampleWorkerResponse;
class ZmqPBExampleWorkerResponseDefaultTypeInternal;
extern ZmqPBExampleWorkerResponseDefaultTypeInternal _ZmqPBExampleWorkerResponse_default_instance_;

namespace protobuf_zmqpbexample_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_zmqpbexample_2eproto

enum RPCError {
  NO_SERVICE = 0,
  NO_METHOD = 1,
  BAD_REQUEST = 2,
  RPCError_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  RPCError_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool RPCError_IsValid(int value);
const RPCError RPCError_MIN = NO_SERVICE;
const RPCError RPCError_MAX = BAD_REQUEST;
const int RPCError_ARRAYSIZE = RPCError_MAX + 1;

const ::google::protobuf::EnumDescriptor* RPCError_descriptor();
inline const ::std::string& RPCError_Name(RPCError value) {
  return ::google::protobuf::internal::NameOfEnum(
    RPCError_descriptor(), value);
}
inline bool RPCError_Parse(
    const ::std::string& name, RPCError* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RPCError>(
    RPCError_descriptor(), name, value);
}
// ===================================================================

class ZmqPBExampleRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ZmqPBExampleRequest) */ {
 public:
  ZmqPBExampleRequest();
  virtual ~ZmqPBExampleRequest();

  ZmqPBExampleRequest(const ZmqPBExampleRequest& from);

  inline ZmqPBExampleRequest& operator=(const ZmqPBExampleRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ZmqPBExampleRequest& default_instance();

  static inline const ZmqPBExampleRequest* internal_default_instance() {
    return reinterpret_cast<const ZmqPBExampleRequest*>(
               &_ZmqPBExampleRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ZmqPBExampleRequest* other);

  // implements Message ----------------------------------------------

  inline ZmqPBExampleRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  ZmqPBExampleRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ZmqPBExampleRequest& from);
  void MergeFrom(const ZmqPBExampleRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ZmqPBExampleRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string request_string = 1;
  void clear_request_string();
  static const int kRequestStringFieldNumber = 1;
  const ::std::string& request_string() const;
  void set_request_string(const ::std::string& value);
  #if LANG_CXX11
  void set_request_string(::std::string&& value);
  #endif
  void set_request_string(const char* value);
  void set_request_string(const char* value, size_t size);
  ::std::string* mutable_request_string();
  ::std::string* release_request_string();
  void set_allocated_request_string(::std::string* request_string);

  // int32 request_number = 2;
  void clear_request_number();
  static const int kRequestNumberFieldNumber = 2;
  ::google::protobuf::int32 request_number() const;
  void set_request_number(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ZmqPBExampleRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr request_string_;
  ::google::protobuf::int32 request_number_;
  mutable int _cached_size_;
  friend struct protobuf_zmqpbexample_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ZmqPBExampleResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ZmqPBExampleResponse) */ {
 public:
  ZmqPBExampleResponse();
  virtual ~ZmqPBExampleResponse();

  ZmqPBExampleResponse(const ZmqPBExampleResponse& from);

  inline ZmqPBExampleResponse& operator=(const ZmqPBExampleResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ZmqPBExampleResponse& default_instance();

  static inline const ZmqPBExampleResponse* internal_default_instance() {
    return reinterpret_cast<const ZmqPBExampleResponse*>(
               &_ZmqPBExampleResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(ZmqPBExampleResponse* other);

  // implements Message ----------------------------------------------

  inline ZmqPBExampleResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  ZmqPBExampleResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ZmqPBExampleResponse& from);
  void MergeFrom(const ZmqPBExampleResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ZmqPBExampleResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string response_string = 1;
  void clear_response_string();
  static const int kResponseStringFieldNumber = 1;
  const ::std::string& response_string() const;
  void set_response_string(const ::std::string& value);
  #if LANG_CXX11
  void set_response_string(::std::string&& value);
  #endif
  void set_response_string(const char* value);
  void set_response_string(const char* value, size_t size);
  ::std::string* mutable_response_string();
  ::std::string* release_response_string();
  void set_allocated_response_string(::std::string* response_string);

  // int32 response_number = 2;
  void clear_response_number();
  static const int kResponseNumberFieldNumber = 2;
  ::google::protobuf::int32 response_number() const;
  void set_response_number(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ZmqPBExampleResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr response_string_;
  ::google::protobuf::int32 response_number_;
  mutable int _cached_size_;
  friend struct protobuf_zmqpbexample_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ZmqPBExampleRPCRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ZmqPBExampleRPCRequest) */ {
 public:
  ZmqPBExampleRPCRequest();
  virtual ~ZmqPBExampleRPCRequest();

  ZmqPBExampleRPCRequest(const ZmqPBExampleRPCRequest& from);

  inline ZmqPBExampleRPCRequest& operator=(const ZmqPBExampleRPCRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ZmqPBExampleRPCRequest& default_instance();

  static inline const ZmqPBExampleRPCRequest* internal_default_instance() {
    return reinterpret_cast<const ZmqPBExampleRPCRequest*>(
               &_ZmqPBExampleRPCRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(ZmqPBExampleRPCRequest* other);

  // implements Message ----------------------------------------------

  inline ZmqPBExampleRPCRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  ZmqPBExampleRPCRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ZmqPBExampleRPCRequest& from);
  void MergeFrom(const ZmqPBExampleRPCRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ZmqPBExampleRPCRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string service = 1;
  void clear_service();
  static const int kServiceFieldNumber = 1;
  const ::std::string& service() const;
  void set_service(const ::std::string& value);
  #if LANG_CXX11
  void set_service(::std::string&& value);
  #endif
  void set_service(const char* value);
  void set_service(const char* value, size_t size);
  ::std::string* mutable_service();
  ::std::string* release_service();
  void set_allocated_service(::std::string* service);

  // string method = 2;
  void clear_method();
  static const int kMethodFieldNumber = 2;
  const ::std::string& method() const;
  void set_method(const ::std::string& value);
  #if LANG_CXX11
  void set_method(::std::string&& value);
  #endif
  void set_method(const char* value);
  void set_method(const char* value, size_t size);
  ::std::string* mutable_method();
  ::std::string* release_method();
  void set_allocated_method(::std::string* method);

  // bytes protobuf = 3;
  void clear_protobuf();
  static const int kProtobufFieldNumber = 3;
  const ::std::string& protobuf() const;
  void set_protobuf(const ::std::string& value);
  #if LANG_CXX11
  void set_protobuf(::std::string&& value);
  #endif
  void set_protobuf(const char* value);
  void set_protobuf(const void* value, size_t size);
  ::std::string* mutable_protobuf();
  ::std::string* release_protobuf();
  void set_allocated_protobuf(::std::string* protobuf);

  // @@protoc_insertion_point(class_scope:ZmqPBExampleRPCRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr service_;
  ::google::protobuf::internal::ArenaStringPtr method_;
  ::google::protobuf::internal::ArenaStringPtr protobuf_;
  mutable int _cached_size_;
  friend struct protobuf_zmqpbexample_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ZmqPBExampleRPCResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ZmqPBExampleRPCResponse) */ {
 public:
  ZmqPBExampleRPCResponse();
  virtual ~ZmqPBExampleRPCResponse();

  ZmqPBExampleRPCResponse(const ZmqPBExampleRPCResponse& from);

  inline ZmqPBExampleRPCResponse& operator=(const ZmqPBExampleRPCResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ZmqPBExampleRPCResponse& default_instance();

  static inline const ZmqPBExampleRPCResponse* internal_default_instance() {
    return reinterpret_cast<const ZmqPBExampleRPCResponse*>(
               &_ZmqPBExampleRPCResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(ZmqPBExampleRPCResponse* other);

  // implements Message ----------------------------------------------

  inline ZmqPBExampleRPCResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  ZmqPBExampleRPCResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ZmqPBExampleRPCResponse& from);
  void MergeFrom(const ZmqPBExampleRPCResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ZmqPBExampleRPCResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes protobuf = 1;
  void clear_protobuf();
  static const int kProtobufFieldNumber = 1;
  const ::std::string& protobuf() const;
  void set_protobuf(const ::std::string& value);
  #if LANG_CXX11
  void set_protobuf(::std::string&& value);
  #endif
  void set_protobuf(const char* value);
  void set_protobuf(const void* value, size_t size);
  ::std::string* mutable_protobuf();
  ::std::string* release_protobuf();
  void set_allocated_protobuf(::std::string* protobuf);

  // string error = 2;
  void clear_error();
  static const int kErrorFieldNumber = 2;
  const ::std::string& error() const;
  void set_error(const ::std::string& value);
  #if LANG_CXX11
  void set_error(::std::string&& value);
  #endif
  void set_error(const char* value);
  void set_error(const char* value, size_t size);
  ::std::string* mutable_error();
  ::std::string* release_error();
  void set_allocated_error(::std::string* error);

  // @@protoc_insertion_point(class_scope:ZmqPBExampleRPCResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr protobuf_;
  ::google::protobuf::internal::ArenaStringPtr error_;
  mutable int _cached_size_;
  friend struct protobuf_zmqpbexample_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RPCAddRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:RPCAddRequest) */ {
 public:
  RPCAddRequest();
  virtual ~RPCAddRequest();

  RPCAddRequest(const RPCAddRequest& from);

  inline RPCAddRequest& operator=(const RPCAddRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RPCAddRequest& default_instance();

  static inline const RPCAddRequest* internal_default_instance() {
    return reinterpret_cast<const RPCAddRequest*>(
               &_RPCAddRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(RPCAddRequest* other);

  // implements Message ----------------------------------------------

  inline RPCAddRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  RPCAddRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RPCAddRequest& from);
  void MergeFrom(const RPCAddRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RPCAddRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 term1 = 1;
  void clear_term1();
  static const int kTerm1FieldNumber = 1;
  ::google::protobuf::uint32 term1() const;
  void set_term1(::google::protobuf::uint32 value);

  // uint32 term2 = 2;
  void clear_term2();
  static const int kTerm2FieldNumber = 2;
  ::google::protobuf::uint32 term2() const;
  void set_term2(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:RPCAddRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 term1_;
  ::google::protobuf::uint32 term2_;
  mutable int _cached_size_;
  friend struct protobuf_zmqpbexample_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RPCAddResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:RPCAddResponse) */ {
 public:
  RPCAddResponse();
  virtual ~RPCAddResponse();

  RPCAddResponse(const RPCAddResponse& from);

  inline RPCAddResponse& operator=(const RPCAddResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RPCAddResponse& default_instance();

  static inline const RPCAddResponse* internal_default_instance() {
    return reinterpret_cast<const RPCAddResponse*>(
               &_RPCAddResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(RPCAddResponse* other);

  // implements Message ----------------------------------------------

  inline RPCAddResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  RPCAddResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RPCAddResponse& from);
  void MergeFrom(const RPCAddResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RPCAddResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 sum = 1;
  void clear_sum();
  static const int kSumFieldNumber = 1;
  ::google::protobuf::uint32 sum() const;
  void set_sum(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:RPCAddResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 sum_;
  mutable int _cached_size_;
  friend struct protobuf_zmqpbexample_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RPCReverseRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:RPCReverseRequest) */ {
 public:
  RPCReverseRequest();
  virtual ~RPCReverseRequest();

  RPCReverseRequest(const RPCReverseRequest& from);

  inline RPCReverseRequest& operator=(const RPCReverseRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RPCReverseRequest& default_instance();

  static inline const RPCReverseRequest* internal_default_instance() {
    return reinterpret_cast<const RPCReverseRequest*>(
               &_RPCReverseRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(RPCReverseRequest* other);

  // implements Message ----------------------------------------------

  inline RPCReverseRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  RPCReverseRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RPCReverseRequest& from);
  void MergeFrom(const RPCReverseRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RPCReverseRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string to_reverse = 1;
  void clear_to_reverse();
  static const int kToReverseFieldNumber = 1;
  const ::std::string& to_reverse() const;
  void set_to_reverse(const ::std::string& value);
  #if LANG_CXX11
  void set_to_reverse(::std::string&& value);
  #endif
  void set_to_reverse(const char* value);
  void set_to_reverse(const char* value, size_t size);
  ::std::string* mutable_to_reverse();
  ::std::string* release_to_reverse();
  void set_allocated_to_reverse(::std::string* to_reverse);

  // @@protoc_insertion_point(class_scope:RPCReverseRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr to_reverse_;
  mutable int _cached_size_;
  friend struct protobuf_zmqpbexample_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RPCReverseResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:RPCReverseResponse) */ {
 public:
  RPCReverseResponse();
  virtual ~RPCReverseResponse();

  RPCReverseResponse(const RPCReverseResponse& from);

  inline RPCReverseResponse& operator=(const RPCReverseResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RPCReverseResponse& default_instance();

  static inline const RPCReverseResponse* internal_default_instance() {
    return reinterpret_cast<const RPCReverseResponse*>(
               &_RPCReverseResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(RPCReverseResponse* other);

  // implements Message ----------------------------------------------

  inline RPCReverseResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  RPCReverseResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RPCReverseResponse& from);
  void MergeFrom(const RPCReverseResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RPCReverseResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string reversed = 1;
  void clear_reversed();
  static const int kReversedFieldNumber = 1;
  const ::std::string& reversed() const;
  void set_reversed(const ::std::string& value);
  #if LANG_CXX11
  void set_reversed(::std::string&& value);
  #endif
  void set_reversed(const char* value);
  void set_reversed(const char* value, size_t size);
  ::std::string* mutable_reversed();
  ::std::string* release_reversed();
  void set_allocated_reversed(::std::string* reversed);

  // @@protoc_insertion_point(class_scope:RPCReverseResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr reversed_;
  mutable int _cached_size_;
  friend struct protobuf_zmqpbexample_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ZmqPBExampleWeather : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ZmqPBExampleWeather) */ {
 public:
  ZmqPBExampleWeather();
  virtual ~ZmqPBExampleWeather();

  ZmqPBExampleWeather(const ZmqPBExampleWeather& from);

  inline ZmqPBExampleWeather& operator=(const ZmqPBExampleWeather& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ZmqPBExampleWeather& default_instance();

  static inline const ZmqPBExampleWeather* internal_default_instance() {
    return reinterpret_cast<const ZmqPBExampleWeather*>(
               &_ZmqPBExampleWeather_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    8;

  void Swap(ZmqPBExampleWeather* other);

  // implements Message ----------------------------------------------

  inline ZmqPBExampleWeather* New() const PROTOBUF_FINAL { return New(NULL); }

  ZmqPBExampleWeather* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ZmqPBExampleWeather& from);
  void MergeFrom(const ZmqPBExampleWeather& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ZmqPBExampleWeather* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 zipcode = 1;
  void clear_zipcode();
  static const int kZipcodeFieldNumber = 1;
  ::google::protobuf::uint32 zipcode() const;
  void set_zipcode(::google::protobuf::uint32 value);

  // uint32 temperature = 2;
  void clear_temperature();
  static const int kTemperatureFieldNumber = 2;
  ::google::protobuf::uint32 temperature() const;
  void set_temperature(::google::protobuf::uint32 value);

  // uint32 relhumidity = 3;
  void clear_relhumidity();
  static const int kRelhumidityFieldNumber = 3;
  ::google::protobuf::uint32 relhumidity() const;
  void set_relhumidity(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:ZmqPBExampleWeather)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 zipcode_;
  ::google::protobuf::uint32 temperature_;
  ::google::protobuf::uint32 relhumidity_;
  mutable int _cached_size_;
  friend struct protobuf_zmqpbexample_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ZmqPBExampleWorkerRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ZmqPBExampleWorkerRequest) */ {
 public:
  ZmqPBExampleWorkerRequest();
  virtual ~ZmqPBExampleWorkerRequest();

  ZmqPBExampleWorkerRequest(const ZmqPBExampleWorkerRequest& from);

  inline ZmqPBExampleWorkerRequest& operator=(const ZmqPBExampleWorkerRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ZmqPBExampleWorkerRequest& default_instance();

  static inline const ZmqPBExampleWorkerRequest* internal_default_instance() {
    return reinterpret_cast<const ZmqPBExampleWorkerRequest*>(
               &_ZmqPBExampleWorkerRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    9;

  void Swap(ZmqPBExampleWorkerRequest* other);

  // implements Message ----------------------------------------------

  inline ZmqPBExampleWorkerRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  ZmqPBExampleWorkerRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ZmqPBExampleWorkerRequest& from);
  void MergeFrom(const ZmqPBExampleWorkerRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ZmqPBExampleWorkerRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string string_in = 1;
  void clear_string_in();
  static const int kStringInFieldNumber = 1;
  const ::std::string& string_in() const;
  void set_string_in(const ::std::string& value);
  #if LANG_CXX11
  void set_string_in(::std::string&& value);
  #endif
  void set_string_in(const char* value);
  void set_string_in(const char* value, size_t size);
  ::std::string* mutable_string_in();
  ::std::string* release_string_in();
  void set_allocated_string_in(::std::string* string_in);

  // @@protoc_insertion_point(class_scope:ZmqPBExampleWorkerRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr string_in_;
  mutable int _cached_size_;
  friend struct protobuf_zmqpbexample_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ZmqPBExampleWorkerResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ZmqPBExampleWorkerResponse) */ {
 public:
  ZmqPBExampleWorkerResponse();
  virtual ~ZmqPBExampleWorkerResponse();

  ZmqPBExampleWorkerResponse(const ZmqPBExampleWorkerResponse& from);

  inline ZmqPBExampleWorkerResponse& operator=(const ZmqPBExampleWorkerResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ZmqPBExampleWorkerResponse& default_instance();

  static inline const ZmqPBExampleWorkerResponse* internal_default_instance() {
    return reinterpret_cast<const ZmqPBExampleWorkerResponse*>(
               &_ZmqPBExampleWorkerResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    10;

  void Swap(ZmqPBExampleWorkerResponse* other);

  // implements Message ----------------------------------------------

  inline ZmqPBExampleWorkerResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  ZmqPBExampleWorkerResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ZmqPBExampleWorkerResponse& from);
  void MergeFrom(const ZmqPBExampleWorkerResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ZmqPBExampleWorkerResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string string_out = 1;
  void clear_string_out();
  static const int kStringOutFieldNumber = 1;
  const ::std::string& string_out() const;
  void set_string_out(const ::std::string& value);
  #if LANG_CXX11
  void set_string_out(::std::string&& value);
  #endif
  void set_string_out(const char* value);
  void set_string_out(const char* value, size_t size);
  ::std::string* mutable_string_out();
  ::std::string* release_string_out();
  void set_allocated_string_out(::std::string* string_out);

  // @@protoc_insertion_point(class_scope:ZmqPBExampleWorkerResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr string_out_;
  mutable int _cached_size_;
  friend struct protobuf_zmqpbexample_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ZmqPBExampleRequest

// string request_string = 1;
inline void ZmqPBExampleRequest::clear_request_string() {
  request_string_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ZmqPBExampleRequest::request_string() const {
  // @@protoc_insertion_point(field_get:ZmqPBExampleRequest.request_string)
  return request_string_.GetNoArena();
}
inline void ZmqPBExampleRequest::set_request_string(const ::std::string& value) {
  
  request_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ZmqPBExampleRequest.request_string)
}
#if LANG_CXX11
inline void ZmqPBExampleRequest::set_request_string(::std::string&& value) {
  
  request_string_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ZmqPBExampleRequest.request_string)
}
#endif
inline void ZmqPBExampleRequest::set_request_string(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  request_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ZmqPBExampleRequest.request_string)
}
inline void ZmqPBExampleRequest::set_request_string(const char* value, size_t size) {
  
  request_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ZmqPBExampleRequest.request_string)
}
inline ::std::string* ZmqPBExampleRequest::mutable_request_string() {
  
  // @@protoc_insertion_point(field_mutable:ZmqPBExampleRequest.request_string)
  return request_string_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ZmqPBExampleRequest::release_request_string() {
  // @@protoc_insertion_point(field_release:ZmqPBExampleRequest.request_string)
  
  return request_string_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ZmqPBExampleRequest::set_allocated_request_string(::std::string* request_string) {
  if (request_string != NULL) {
    
  } else {
    
  }
  request_string_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), request_string);
  // @@protoc_insertion_point(field_set_allocated:ZmqPBExampleRequest.request_string)
}

// int32 request_number = 2;
inline void ZmqPBExampleRequest::clear_request_number() {
  request_number_ = 0;
}
inline ::google::protobuf::int32 ZmqPBExampleRequest::request_number() const {
  // @@protoc_insertion_point(field_get:ZmqPBExampleRequest.request_number)
  return request_number_;
}
inline void ZmqPBExampleRequest::set_request_number(::google::protobuf::int32 value) {
  
  request_number_ = value;
  // @@protoc_insertion_point(field_set:ZmqPBExampleRequest.request_number)
}

// -------------------------------------------------------------------

// ZmqPBExampleResponse

// string response_string = 1;
inline void ZmqPBExampleResponse::clear_response_string() {
  response_string_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ZmqPBExampleResponse::response_string() const {
  // @@protoc_insertion_point(field_get:ZmqPBExampleResponse.response_string)
  return response_string_.GetNoArena();
}
inline void ZmqPBExampleResponse::set_response_string(const ::std::string& value) {
  
  response_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ZmqPBExampleResponse.response_string)
}
#if LANG_CXX11
inline void ZmqPBExampleResponse::set_response_string(::std::string&& value) {
  
  response_string_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ZmqPBExampleResponse.response_string)
}
#endif
inline void ZmqPBExampleResponse::set_response_string(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  response_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ZmqPBExampleResponse.response_string)
}
inline void ZmqPBExampleResponse::set_response_string(const char* value, size_t size) {
  
  response_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ZmqPBExampleResponse.response_string)
}
inline ::std::string* ZmqPBExampleResponse::mutable_response_string() {
  
  // @@protoc_insertion_point(field_mutable:ZmqPBExampleResponse.response_string)
  return response_string_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ZmqPBExampleResponse::release_response_string() {
  // @@protoc_insertion_point(field_release:ZmqPBExampleResponse.response_string)
  
  return response_string_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ZmqPBExampleResponse::set_allocated_response_string(::std::string* response_string) {
  if (response_string != NULL) {
    
  } else {
    
  }
  response_string_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), response_string);
  // @@protoc_insertion_point(field_set_allocated:ZmqPBExampleResponse.response_string)
}

// int32 response_number = 2;
inline void ZmqPBExampleResponse::clear_response_number() {
  response_number_ = 0;
}
inline ::google::protobuf::int32 ZmqPBExampleResponse::response_number() const {
  // @@protoc_insertion_point(field_get:ZmqPBExampleResponse.response_number)
  return response_number_;
}
inline void ZmqPBExampleResponse::set_response_number(::google::protobuf::int32 value) {
  
  response_number_ = value;
  // @@protoc_insertion_point(field_set:ZmqPBExampleResponse.response_number)
}

// -------------------------------------------------------------------

// ZmqPBExampleRPCRequest

// string service = 1;
inline void ZmqPBExampleRPCRequest::clear_service() {
  service_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ZmqPBExampleRPCRequest::service() const {
  // @@protoc_insertion_point(field_get:ZmqPBExampleRPCRequest.service)
  return service_.GetNoArena();
}
inline void ZmqPBExampleRPCRequest::set_service(const ::std::string& value) {
  
  service_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ZmqPBExampleRPCRequest.service)
}
#if LANG_CXX11
inline void ZmqPBExampleRPCRequest::set_service(::std::string&& value) {
  
  service_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ZmqPBExampleRPCRequest.service)
}
#endif
inline void ZmqPBExampleRPCRequest::set_service(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  service_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ZmqPBExampleRPCRequest.service)
}
inline void ZmqPBExampleRPCRequest::set_service(const char* value, size_t size) {
  
  service_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ZmqPBExampleRPCRequest.service)
}
inline ::std::string* ZmqPBExampleRPCRequest::mutable_service() {
  
  // @@protoc_insertion_point(field_mutable:ZmqPBExampleRPCRequest.service)
  return service_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ZmqPBExampleRPCRequest::release_service() {
  // @@protoc_insertion_point(field_release:ZmqPBExampleRPCRequest.service)
  
  return service_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ZmqPBExampleRPCRequest::set_allocated_service(::std::string* service) {
  if (service != NULL) {
    
  } else {
    
  }
  service_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), service);
  // @@protoc_insertion_point(field_set_allocated:ZmqPBExampleRPCRequest.service)
}

// string method = 2;
inline void ZmqPBExampleRPCRequest::clear_method() {
  method_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ZmqPBExampleRPCRequest::method() const {
  // @@protoc_insertion_point(field_get:ZmqPBExampleRPCRequest.method)
  return method_.GetNoArena();
}
inline void ZmqPBExampleRPCRequest::set_method(const ::std::string& value) {
  
  method_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ZmqPBExampleRPCRequest.method)
}
#if LANG_CXX11
inline void ZmqPBExampleRPCRequest::set_method(::std::string&& value) {
  
  method_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ZmqPBExampleRPCRequest.method)
}
#endif
inline void ZmqPBExampleRPCRequest::set_method(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  method_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ZmqPBExampleRPCRequest.method)
}
inline void ZmqPBExampleRPCRequest::set_method(const char* value, size_t size) {
  
  method_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ZmqPBExampleRPCRequest.method)
}
inline ::std::string* ZmqPBExampleRPCRequest::mutable_method() {
  
  // @@protoc_insertion_point(field_mutable:ZmqPBExampleRPCRequest.method)
  return method_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ZmqPBExampleRPCRequest::release_method() {
  // @@protoc_insertion_point(field_release:ZmqPBExampleRPCRequest.method)
  
  return method_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ZmqPBExampleRPCRequest::set_allocated_method(::std::string* method) {
  if (method != NULL) {
    
  } else {
    
  }
  method_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), method);
  // @@protoc_insertion_point(field_set_allocated:ZmqPBExampleRPCRequest.method)
}

// bytes protobuf = 3;
inline void ZmqPBExampleRPCRequest::clear_protobuf() {
  protobuf_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ZmqPBExampleRPCRequest::protobuf() const {
  // @@protoc_insertion_point(field_get:ZmqPBExampleRPCRequest.protobuf)
  return protobuf_.GetNoArena();
}
inline void ZmqPBExampleRPCRequest::set_protobuf(const ::std::string& value) {
  
  protobuf_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ZmqPBExampleRPCRequest.protobuf)
}
#if LANG_CXX11
inline void ZmqPBExampleRPCRequest::set_protobuf(::std::string&& value) {
  
  protobuf_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ZmqPBExampleRPCRequest.protobuf)
}
#endif
inline void ZmqPBExampleRPCRequest::set_protobuf(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  protobuf_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ZmqPBExampleRPCRequest.protobuf)
}
inline void ZmqPBExampleRPCRequest::set_protobuf(const void* value, size_t size) {
  
  protobuf_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ZmqPBExampleRPCRequest.protobuf)
}
inline ::std::string* ZmqPBExampleRPCRequest::mutable_protobuf() {
  
  // @@protoc_insertion_point(field_mutable:ZmqPBExampleRPCRequest.protobuf)
  return protobuf_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ZmqPBExampleRPCRequest::release_protobuf() {
  // @@protoc_insertion_point(field_release:ZmqPBExampleRPCRequest.protobuf)
  
  return protobuf_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ZmqPBExampleRPCRequest::set_allocated_protobuf(::std::string* protobuf) {
  if (protobuf != NULL) {
    
  } else {
    
  }
  protobuf_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), protobuf);
  // @@protoc_insertion_point(field_set_allocated:ZmqPBExampleRPCRequest.protobuf)
}

// -------------------------------------------------------------------

// ZmqPBExampleRPCResponse

// bytes protobuf = 1;
inline void ZmqPBExampleRPCResponse::clear_protobuf() {
  protobuf_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ZmqPBExampleRPCResponse::protobuf() const {
  // @@protoc_insertion_point(field_get:ZmqPBExampleRPCResponse.protobuf)
  return protobuf_.GetNoArena();
}
inline void ZmqPBExampleRPCResponse::set_protobuf(const ::std::string& value) {
  
  protobuf_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ZmqPBExampleRPCResponse.protobuf)
}
#if LANG_CXX11
inline void ZmqPBExampleRPCResponse::set_protobuf(::std::string&& value) {
  
  protobuf_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ZmqPBExampleRPCResponse.protobuf)
}
#endif
inline void ZmqPBExampleRPCResponse::set_protobuf(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  protobuf_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ZmqPBExampleRPCResponse.protobuf)
}
inline void ZmqPBExampleRPCResponse::set_protobuf(const void* value, size_t size) {
  
  protobuf_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ZmqPBExampleRPCResponse.protobuf)
}
inline ::std::string* ZmqPBExampleRPCResponse::mutable_protobuf() {
  
  // @@protoc_insertion_point(field_mutable:ZmqPBExampleRPCResponse.protobuf)
  return protobuf_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ZmqPBExampleRPCResponse::release_protobuf() {
  // @@protoc_insertion_point(field_release:ZmqPBExampleRPCResponse.protobuf)
  
  return protobuf_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ZmqPBExampleRPCResponse::set_allocated_protobuf(::std::string* protobuf) {
  if (protobuf != NULL) {
    
  } else {
    
  }
  protobuf_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), protobuf);
  // @@protoc_insertion_point(field_set_allocated:ZmqPBExampleRPCResponse.protobuf)
}

// string error = 2;
inline void ZmqPBExampleRPCResponse::clear_error() {
  error_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ZmqPBExampleRPCResponse::error() const {
  // @@protoc_insertion_point(field_get:ZmqPBExampleRPCResponse.error)
  return error_.GetNoArena();
}
inline void ZmqPBExampleRPCResponse::set_error(const ::std::string& value) {
  
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ZmqPBExampleRPCResponse.error)
}
#if LANG_CXX11
inline void ZmqPBExampleRPCResponse::set_error(::std::string&& value) {
  
  error_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ZmqPBExampleRPCResponse.error)
}
#endif
inline void ZmqPBExampleRPCResponse::set_error(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ZmqPBExampleRPCResponse.error)
}
inline void ZmqPBExampleRPCResponse::set_error(const char* value, size_t size) {
  
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ZmqPBExampleRPCResponse.error)
}
inline ::std::string* ZmqPBExampleRPCResponse::mutable_error() {
  
  // @@protoc_insertion_point(field_mutable:ZmqPBExampleRPCResponse.error)
  return error_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ZmqPBExampleRPCResponse::release_error() {
  // @@protoc_insertion_point(field_release:ZmqPBExampleRPCResponse.error)
  
  return error_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ZmqPBExampleRPCResponse::set_allocated_error(::std::string* error) {
  if (error != NULL) {
    
  } else {
    
  }
  error_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error);
  // @@protoc_insertion_point(field_set_allocated:ZmqPBExampleRPCResponse.error)
}

// -------------------------------------------------------------------

// RPCAddRequest

// uint32 term1 = 1;
inline void RPCAddRequest::clear_term1() {
  term1_ = 0u;
}
inline ::google::protobuf::uint32 RPCAddRequest::term1() const {
  // @@protoc_insertion_point(field_get:RPCAddRequest.term1)
  return term1_;
}
inline void RPCAddRequest::set_term1(::google::protobuf::uint32 value) {
  
  term1_ = value;
  // @@protoc_insertion_point(field_set:RPCAddRequest.term1)
}

// uint32 term2 = 2;
inline void RPCAddRequest::clear_term2() {
  term2_ = 0u;
}
inline ::google::protobuf::uint32 RPCAddRequest::term2() const {
  // @@protoc_insertion_point(field_get:RPCAddRequest.term2)
  return term2_;
}
inline void RPCAddRequest::set_term2(::google::protobuf::uint32 value) {
  
  term2_ = value;
  // @@protoc_insertion_point(field_set:RPCAddRequest.term2)
}

// -------------------------------------------------------------------

// RPCAddResponse

// uint32 sum = 1;
inline void RPCAddResponse::clear_sum() {
  sum_ = 0u;
}
inline ::google::protobuf::uint32 RPCAddResponse::sum() const {
  // @@protoc_insertion_point(field_get:RPCAddResponse.sum)
  return sum_;
}
inline void RPCAddResponse::set_sum(::google::protobuf::uint32 value) {
  
  sum_ = value;
  // @@protoc_insertion_point(field_set:RPCAddResponse.sum)
}

// -------------------------------------------------------------------

// RPCReverseRequest

// string to_reverse = 1;
inline void RPCReverseRequest::clear_to_reverse() {
  to_reverse_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RPCReverseRequest::to_reverse() const {
  // @@protoc_insertion_point(field_get:RPCReverseRequest.to_reverse)
  return to_reverse_.GetNoArena();
}
inline void RPCReverseRequest::set_to_reverse(const ::std::string& value) {
  
  to_reverse_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:RPCReverseRequest.to_reverse)
}
#if LANG_CXX11
inline void RPCReverseRequest::set_to_reverse(::std::string&& value) {
  
  to_reverse_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:RPCReverseRequest.to_reverse)
}
#endif
inline void RPCReverseRequest::set_to_reverse(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  to_reverse_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:RPCReverseRequest.to_reverse)
}
inline void RPCReverseRequest::set_to_reverse(const char* value, size_t size) {
  
  to_reverse_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:RPCReverseRequest.to_reverse)
}
inline ::std::string* RPCReverseRequest::mutable_to_reverse() {
  
  // @@protoc_insertion_point(field_mutable:RPCReverseRequest.to_reverse)
  return to_reverse_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RPCReverseRequest::release_to_reverse() {
  // @@protoc_insertion_point(field_release:RPCReverseRequest.to_reverse)
  
  return to_reverse_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RPCReverseRequest::set_allocated_to_reverse(::std::string* to_reverse) {
  if (to_reverse != NULL) {
    
  } else {
    
  }
  to_reverse_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), to_reverse);
  // @@protoc_insertion_point(field_set_allocated:RPCReverseRequest.to_reverse)
}

// -------------------------------------------------------------------

// RPCReverseResponse

// string reversed = 1;
inline void RPCReverseResponse::clear_reversed() {
  reversed_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RPCReverseResponse::reversed() const {
  // @@protoc_insertion_point(field_get:RPCReverseResponse.reversed)
  return reversed_.GetNoArena();
}
inline void RPCReverseResponse::set_reversed(const ::std::string& value) {
  
  reversed_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:RPCReverseResponse.reversed)
}
#if LANG_CXX11
inline void RPCReverseResponse::set_reversed(::std::string&& value) {
  
  reversed_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:RPCReverseResponse.reversed)
}
#endif
inline void RPCReverseResponse::set_reversed(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  reversed_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:RPCReverseResponse.reversed)
}
inline void RPCReverseResponse::set_reversed(const char* value, size_t size) {
  
  reversed_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:RPCReverseResponse.reversed)
}
inline ::std::string* RPCReverseResponse::mutable_reversed() {
  
  // @@protoc_insertion_point(field_mutable:RPCReverseResponse.reversed)
  return reversed_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RPCReverseResponse::release_reversed() {
  // @@protoc_insertion_point(field_release:RPCReverseResponse.reversed)
  
  return reversed_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RPCReverseResponse::set_allocated_reversed(::std::string* reversed) {
  if (reversed != NULL) {
    
  } else {
    
  }
  reversed_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), reversed);
  // @@protoc_insertion_point(field_set_allocated:RPCReverseResponse.reversed)
}

// -------------------------------------------------------------------

// ZmqPBExampleWeather

// uint32 zipcode = 1;
inline void ZmqPBExampleWeather::clear_zipcode() {
  zipcode_ = 0u;
}
inline ::google::protobuf::uint32 ZmqPBExampleWeather::zipcode() const {
  // @@protoc_insertion_point(field_get:ZmqPBExampleWeather.zipcode)
  return zipcode_;
}
inline void ZmqPBExampleWeather::set_zipcode(::google::protobuf::uint32 value) {
  
  zipcode_ = value;
  // @@protoc_insertion_point(field_set:ZmqPBExampleWeather.zipcode)
}

// uint32 temperature = 2;
inline void ZmqPBExampleWeather::clear_temperature() {
  temperature_ = 0u;
}
inline ::google::protobuf::uint32 ZmqPBExampleWeather::temperature() const {
  // @@protoc_insertion_point(field_get:ZmqPBExampleWeather.temperature)
  return temperature_;
}
inline void ZmqPBExampleWeather::set_temperature(::google::protobuf::uint32 value) {
  
  temperature_ = value;
  // @@protoc_insertion_point(field_set:ZmqPBExampleWeather.temperature)
}

// uint32 relhumidity = 3;
inline void ZmqPBExampleWeather::clear_relhumidity() {
  relhumidity_ = 0u;
}
inline ::google::protobuf::uint32 ZmqPBExampleWeather::relhumidity() const {
  // @@protoc_insertion_point(field_get:ZmqPBExampleWeather.relhumidity)
  return relhumidity_;
}
inline void ZmqPBExampleWeather::set_relhumidity(::google::protobuf::uint32 value) {
  
  relhumidity_ = value;
  // @@protoc_insertion_point(field_set:ZmqPBExampleWeather.relhumidity)
}

// -------------------------------------------------------------------

// ZmqPBExampleWorkerRequest

// string string_in = 1;
inline void ZmqPBExampleWorkerRequest::clear_string_in() {
  string_in_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ZmqPBExampleWorkerRequest::string_in() const {
  // @@protoc_insertion_point(field_get:ZmqPBExampleWorkerRequest.string_in)
  return string_in_.GetNoArena();
}
inline void ZmqPBExampleWorkerRequest::set_string_in(const ::std::string& value) {
  
  string_in_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ZmqPBExampleWorkerRequest.string_in)
}
#if LANG_CXX11
inline void ZmqPBExampleWorkerRequest::set_string_in(::std::string&& value) {
  
  string_in_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ZmqPBExampleWorkerRequest.string_in)
}
#endif
inline void ZmqPBExampleWorkerRequest::set_string_in(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  string_in_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ZmqPBExampleWorkerRequest.string_in)
}
inline void ZmqPBExampleWorkerRequest::set_string_in(const char* value, size_t size) {
  
  string_in_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ZmqPBExampleWorkerRequest.string_in)
}
inline ::std::string* ZmqPBExampleWorkerRequest::mutable_string_in() {
  
  // @@protoc_insertion_point(field_mutable:ZmqPBExampleWorkerRequest.string_in)
  return string_in_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ZmqPBExampleWorkerRequest::release_string_in() {
  // @@protoc_insertion_point(field_release:ZmqPBExampleWorkerRequest.string_in)
  
  return string_in_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ZmqPBExampleWorkerRequest::set_allocated_string_in(::std::string* string_in) {
  if (string_in != NULL) {
    
  } else {
    
  }
  string_in_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), string_in);
  // @@protoc_insertion_point(field_set_allocated:ZmqPBExampleWorkerRequest.string_in)
}

// -------------------------------------------------------------------

// ZmqPBExampleWorkerResponse

// string string_out = 1;
inline void ZmqPBExampleWorkerResponse::clear_string_out() {
  string_out_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ZmqPBExampleWorkerResponse::string_out() const {
  // @@protoc_insertion_point(field_get:ZmqPBExampleWorkerResponse.string_out)
  return string_out_.GetNoArena();
}
inline void ZmqPBExampleWorkerResponse::set_string_out(const ::std::string& value) {
  
  string_out_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ZmqPBExampleWorkerResponse.string_out)
}
#if LANG_CXX11
inline void ZmqPBExampleWorkerResponse::set_string_out(::std::string&& value) {
  
  string_out_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ZmqPBExampleWorkerResponse.string_out)
}
#endif
inline void ZmqPBExampleWorkerResponse::set_string_out(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  string_out_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ZmqPBExampleWorkerResponse.string_out)
}
inline void ZmqPBExampleWorkerResponse::set_string_out(const char* value, size_t size) {
  
  string_out_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ZmqPBExampleWorkerResponse.string_out)
}
inline ::std::string* ZmqPBExampleWorkerResponse::mutable_string_out() {
  
  // @@protoc_insertion_point(field_mutable:ZmqPBExampleWorkerResponse.string_out)
  return string_out_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ZmqPBExampleWorkerResponse::release_string_out() {
  // @@protoc_insertion_point(field_release:ZmqPBExampleWorkerResponse.string_out)
  
  return string_out_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ZmqPBExampleWorkerResponse::set_allocated_string_out(::std::string* string_out) {
  if (string_out != NULL) {
    
  } else {
    
  }
  string_out_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), string_out);
  // @@protoc_insertion_point(field_set_allocated:ZmqPBExampleWorkerResponse.string_out)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::RPCError> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::RPCError>() {
  return ::RPCError_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_zmqpbexample_2eproto__INCLUDED
