// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "zmqpbexample.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* ZmqPBExample_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ZmqPBExample_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_zmqpbexample_2eproto() {
  protobuf_AddDesc_zmqpbexample_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "zmqpbexample.proto");
  GOOGLE_CHECK(file != NULL);
  ZmqPBExample_descriptor_ = file->message_type(0);
  static const int ZmqPBExample_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ZmqPBExample, foo_),
  };
  ZmqPBExample_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ZmqPBExample_descriptor_,
      ZmqPBExample::default_instance_,
      ZmqPBExample_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ZmqPBExample, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ZmqPBExample, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ZmqPBExample));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_zmqpbexample_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ZmqPBExample_descriptor_, &ZmqPBExample::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_zmqpbexample_2eproto() {
  delete ZmqPBExample::default_instance_;
  delete ZmqPBExample_reflection_;
}

void protobuf_AddDesc_zmqpbexample_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022zmqpbexample.proto\"\033\n\014ZmqPBExample\022\013\n\003"
    "foo\030\001 \002(\t", 49);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "zmqpbexample.proto", &protobuf_RegisterTypes);
  ZmqPBExample::default_instance_ = new ZmqPBExample();
  ZmqPBExample::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_zmqpbexample_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_zmqpbexample_2eproto {
  StaticDescriptorInitializer_zmqpbexample_2eproto() {
    protobuf_AddDesc_zmqpbexample_2eproto();
  }
} static_descriptor_initializer_zmqpbexample_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int ZmqPBExample::kFooFieldNumber;
#endif  // !_MSC_VER

ZmqPBExample::ZmqPBExample()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ZmqPBExample::InitAsDefaultInstance() {
}

ZmqPBExample::ZmqPBExample(const ZmqPBExample& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ZmqPBExample::SharedCtor() {
  _cached_size_ = 0;
  foo_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ZmqPBExample::~ZmqPBExample() {
  SharedDtor();
}

void ZmqPBExample::SharedDtor() {
  if (foo_ != &::google::protobuf::internal::kEmptyString) {
    delete foo_;
  }
  if (this != default_instance_) {
  }
}

void ZmqPBExample::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ZmqPBExample::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ZmqPBExample_descriptor_;
}

const ZmqPBExample& ZmqPBExample::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_zmqpbexample_2eproto();  return *default_instance_;
}

ZmqPBExample* ZmqPBExample::default_instance_ = NULL;

ZmqPBExample* ZmqPBExample::New() const {
  return new ZmqPBExample;
}

void ZmqPBExample::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_foo()) {
      if (foo_ != &::google::protobuf::internal::kEmptyString) {
        foo_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ZmqPBExample::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string foo = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_foo()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->foo().data(), this->foo().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ZmqPBExample::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string foo = 1;
  if (has_foo()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->foo().data(), this->foo().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->foo(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ZmqPBExample::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string foo = 1;
  if (has_foo()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->foo().data(), this->foo().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->foo(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ZmqPBExample::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string foo = 1;
    if (has_foo()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->foo());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ZmqPBExample::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ZmqPBExample* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ZmqPBExample*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ZmqPBExample::MergeFrom(const ZmqPBExample& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_foo()) {
      set_foo(from.foo());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ZmqPBExample::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ZmqPBExample::CopyFrom(const ZmqPBExample& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ZmqPBExample::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  return true;
}

void ZmqPBExample::Swap(ZmqPBExample* other) {
  if (other != this) {
    std::swap(foo_, other->foo_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ZmqPBExample::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ZmqPBExample_descriptor_;
  metadata.reflection = ZmqPBExample_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
